# Primera funci√≥n 2 errores
a = 1
b = 2
print(b)
